// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtaxvgXE3I6o8F8sHZbAn-rf9YxLZ2REQ',
    appId: '1:354108231052:android:69fc5c512d7e4bb3695aa9',
    messagingSenderId: '354108231052',
    projectId: 'erpsystem-d5608',
    storageBucket: 'erpsystem-d5608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiphpHp3GBSdR4RnbsGOSDc9rs47y5Ses',
    appId: '1:354108231052:ios:6f91620966e7a94d695aa9',
    messagingSenderId: '354108231052',
    projectId: 'erpsystem-d5608',
    storageBucket: 'erpsystem-d5608.firebasestorage.app',
    iosBundleId: 'com.example.dealtrackuser',
  );
}
